.\"
.\" Copyright (c) 2019 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt OPENRSYNC 1
.Os
.Sh NAME
.Nm openrsync
.Nd synchronise local and remote files
.Sh SYNOPSIS
.Nm openrsync
.Op Fl CDLPRSacdgklnoprtuvx
.Op Fl e Ar program
.Op Fl f Ar filter
.Op Fl -address Ns = Ns Ar sourceaddr
.Op Fl -append
.Op Fl -backup
.Op Fl -bwlimit Ns = Ns limit
.Op Fl -compare-dest Ns = Ns Ar directory
.Op Fl -del
.Op Fl -delay-updates
.Op Fl -delete-before
.Op Fl -delete-during
.Op Fl -delete-delay
.Op Fl -delete-after
.Op Fl -delete-excluded
.Op Fl -exclude Ar pattern
.Op Fl -exclude-from Ns = Ns Ar file
.Op Fl -ignore-existing
.Op Fl -ignore-non-existing
.Op Fl -include Ar pattern
.Op Fl -include-from Ns = Ns Ar file
.Op Fl -inplace
.Op Fl -link-dest Ns = Ns Ar directory
.Op Fl -max-size Ns = Ns size
.Op Fl -min-size Ns = Ns size
.Op Fl -no-motd
.Op Fl -numeric-ids
.Op Fl -partial
.Op Fl -port Ns = Ns Ar service
.Op Fl -progress
.Op Fl -remove-source-files
.Op Fl -rsync-path Ns = Ns Ar program
.Op Fl -super
.Op Fl -timeout Ns = Ns Ar seconds
.Op Fl -version
.Ar source ...
.Ar directory
.Sh DESCRIPTION
The
.Nm
utility synchronises files in the destination
.Ar directory
with one or more
.Ar source
files.
Either the
.Ar source
or the destination
.Ar directory
may be remote,
but not both.
The arguments are as follows:
.Bl -tag -width Ds
.It Fl a , -archive
Shorthand for
.Fl Dgloprt .
.It Fl -address Ns = Ns Ar sourceaddr
When connecting to an rsync daemon, use
.Ar sourceaddr
as the source address for connections, which is useful on machines with
multiple interfaces.
.It Fl -append
If the destination file exists and is shorter than the source file then rsync
will append the difference to the destination file.
If after the transfer the whole-file checksums do not match then the
destination file will be updated via the usual block-based delta-merge
protocol.
This option implies
.Fl -inplace .
.It Fl b , -backup
Make a backup of changed files with ~ suffix.
.It Fl -bwlimit Ar limit
Limit transfer speed to
.Ar limit
bytes/sec.
The
.Ar limit
may also contain any of the suffixes described in the
.Fl -max-size
definition of size.
.It Fl c , -checksum
Use full-file checksums to determine which files have changed and should
be transferred, rather than the usual file size and modification time
"quick check".
.It Fl -compare-dest Ns = Ns Ar directory
Use directory as an alternate base directory to compare files against on the
destination machine.
If file in
.Ar directory
is found and identical to the sender's file, the file will not be transferred.
Multiple
.Fl -compare-dest
directories may be provided.
If
.Ar directory
is a relative path, it is relative to the destination directory.
.It Fl L , -copy-links
Copy targets of symbolic links.
.It Fl k , -copy-dirlinks
Copy targets of symbolic links that point to directories only.
.It Fl C , Fl -cvs-exclude
Exclude a common list of files as CVS would.
The patterns deployed are specifically:
.Bl -column -offset indent ".make.state" ".nse_depinfo" "*.BAK" "CVS.adm"
.It RCS         Ta SCCS         Ta CVS   Ta CVS.adm
.It RCSLOG      Ta cvslog.*     Ta tags  Ta TAGS
.It .make.state Ta .nse_depinfo Ta *~    Ta #*
.It .#*         Ta ,*           Ta _$*   Ta *$
.It *.old       Ta *.bak        Ta *.BAK Ta *.orig
.It *.rej       Ta .del-*       Ta *.a   Ta *.olb
.It *.o         Ta *.obj        Ta *.so  Ta *.exe
.It *.Z         Ta *.elc        Ta *.ln  Ta core
.It .svn/       Ta              Ta       Ta
.El
Followed by any patterns included in
.Pa $HOME/.cvsignore
and the
.Ev CVSIGNORE
environment variable.
.Pp
The
.Fl C
flag also adds a
.Dq dir-merge
CVS rule to include per-dir
.Pa .cvsignore
files.
All of these rules are appended to the end of the filter list with the
equivalent of specifying
.Fl f Dq Ar -C
.Fl f Dq Ar :C .
.It Fl D
Also transfer device and special files.
Shorthand for
.Fl -devices -specials .
.It Fl -del , -delete
Delete files in
.Ar directory
not found in
.Ar source
directories.
Only applicable with
.Fl r .
.It Fl -delay-updates
Delay updates of (only) plain files until all other operations
are complete.
This is done to be more atomic.
Requires extra space in the destination directory up to the amount of the
whole tree.
.It Fl -delete-before
Execute the above described
.Fl -delete
behavior before the transfer begins.
This is the default timing when
.It Fl -delete
is used.
This option is mutually exclusive with
.Fl -delete-during ,
.Fl -delete-delay ,
and
.Fl -delete-after .
.It Fl -delete-during
Execute the above described
.Fl -delete
behavior as the transfer happens, right before each directory to be transferred
is checked for updates.
This option is mutually exclusive with
.Fl -delete-before ,
.Fl -delete-delay ,
and
.Fl -delete-after .
.It Fl -delete-delay
Execute the above described
.Fl -delete
behavior after the transfer happens, but collect the list to be deleted right
before each directory to be transferred is checked for updates.
This option is mutually exclusive with
.Fl -delete-before ,
.Fl -delete-during ,
and
.Fl -delete-after .
.It Fl -delete-after
Execute the above described
.Fl -delete
behavior after the transfer has completed.
This option is mutually exclusive with
.Fl -delete-before ,
.Fl -delete-during ,
and
.Fl -delete-delay .
.It Fl -delete-excluded
When used in combination with any one of the above
.Fl -delete
options, supplied
.Fl -exclude
patterns will not prevent a file from being deleted.
.It Fl -exclude Ar pattern
Exclude files matching
.Em pattern .
.It Fl -exclude-from Ns = Ns Ar file
Load
.Em patterns
and
.Em rules
from
.Em file .
.It Fl -ignore-existing
Ignore files that already exist.
.It Fl -ignore-non-existing , Fl -existing
Ignore files that do not already exist (do not create them).
.It Fl I -ignore-times
Do not skip based on file size and modification time.
.It Fl -include Ar pattern
Include files matching
.Em pattern .
.It Fl -include-from Ns = Ns Ar file
Load
.Em patterns
and
.Em rules
from
.Em file .
.It Fl -devices
Also transfer device files.
.It Fl e Ar program , Fl -rsh Ns = Ns Ar program
Specify alternative communication program, defaults to
.Xr ssh 1 .
The
.Ev RSYNC_RSH
environment variable will be used if an
.Fl e
option is not present.
Note that
.Nm
will generally handle quotes, but it makes no attempt to deal with escape
sequences.
In particular, escaped quotation marks will not be escaped.
.It Fl f Ar filter , Fl -filter Ns = Ns Ar filter
Process
.Ar filter
against the global filter chain.
The specified
.Ar filter
may be a rule to include a filter file, or to include a per-directory filter
file.
Regular filter files are processed immediately, while per-directory filter files
are processed as directories are encountered.
See
.Sx PATTERNS AND RULES
for more details about the syntax and capabilities of
.Nm
filters.
.It Fl g , -group
Set the group name to match the source.
For example, group
.Qq kristaps
with ID 1000 on a remote server is matched to group
.Qq kristaps
on the local machine with ID 2000.
If
.Fl -numeric-ids
is also given or if the remote group name is unknown on the local machine,
set the numeric group ID to match the source instead.
.It Fl l , -links
Also transfer symbolic links.
The link is transferred as a standalone file: if the destination does
not exist, it will be broken.
.It Fl -inplace
Avoid creating temporary files, instead operating on files directly in place
in the destination.
This option has some notable trade-offs that must be considered prior to using
it.
For example, hardlinks will not be broken even if a file is no longer hardlinked
in the source directory.
.It Fl -link-dest Ns = Ns Ar directory
Use directory as an alternate base directory to compare files against on the
destination machine.
If file in
.Ar directory
is found and identical to the sender's file, the file will be hardlinked.
Multiple
.Fl -compare-dest
directories may be provided.
If
.Ar directory
is a relative path, it is relative to the destination directory.
.It Fl -max-size Ar size
Don't transfer any file that is larger than
.Ar size
bytes.
Alternatively
.Ar size
may instead use a multiplier (such as
0B, 100B, 1023B, 1K, 1.5K, 5.5M; or any sequence with a case-insensitive
terminal scale multiplier of B, K, M, G, T, P, or E; corresponding to bytes,
kilobytes, and so on)
to specify the size.
.It Fl -min-size Ar size
Don't transfer any file that is smaller than
.Ar size
bytes.
See
.Fl -max-size
on the definition of size.
.It Fl n , -dry-run
Do not actually modify the destination.
Mainly useful in combination with
.Fl v .
.It Fl -no-motd
Do not display the Message of the Day.
.It Fl -numeric-ids
Ignore user and group names, use numeric user and group IDs only.
Has no effect unless
.Fl g
or
.Fl o
is also given.
.It Fl o , -owner
Set the user name to match the source, with similar matching logic as for
.Fl g .
If
.Fl -numeric-ids
is also given or if the remote user name is unknown on the local machine,
set the numeric user ID to match the source instead.
Only works if run as root.
.It Fl p , -perms
Set destination file or directory permissions to match the source when
it is updated.
.It Fl -partial
Do not remove partially transferred files if
.Nm
is interrupted, which opens up the possibility for them to be easily resumed
later.
.It Fl -port Ns = Ns Ar service
Specify an alternative TCP port number.
The
.Ar service
can be given as a decimal integer or as a name to be looked up in the
.Xr services 5
database.
The default is
.Dq rsync .
.It Fl -progress
Periodically report file transfer progress.
.It Fl r , -recursive
If
.Ar source
designates a directory, synchronise the directory and the entire subtree
connected at that point.
If
.Ar source
ends with a slash, only the subtree is synchronised, not the
.Ar source
directory itself.
If
.Ar source
is a file, this has no effect.
.It Fl -remove-source-files
Remove
.Ar source
files as they are transferred into
.Ar directory .
Files are only removed once they are confirmed to be fully in place.
By default
.Nm
will delete files as the transfer progresses, but given its asynchronous nature
there may be a noticeable delay between a given file finishing its transfer and
its subsequent removal.
.Pp
When combined with
.Fl -delay-updates ,
files will be removed in a larger batch toward the end of the transfer.
.It Fl R , -relative
Normally, pathnames on the commandline omit the directory components.
This option will include the dir components.
.It Fl -rsync-path Ns = Ns Ar program
Run
.Ar program
on the remote host instead of the default
.Pa rsync .
.It Fl -specials
Also transfer fifo and unix domain socket files.
.It Fl S , -sparse
Attempt to efficiently handle sparse files.
.It Fl -super
Always attempt traditionally super-user activities.
This flag mostly interacts with the
.Fl -owner ,
.Fl -group ,
and
.Fl -devices
options, which may be permitted to unprivileged users on the receiving end in
some configurations.
.Fl -no-super
is also supported to avoid them entirely.
.It Fl -timeout Ns = Ns Ar seconds
Set the I/O timeout in seconds.
Exit if no data was transferred for the specified time.
The default is 0, which means no timeout.
.It Fl t , -times
Set destination file and directory modification time to match the source
when it is updated or created.
.It Fl u , -update
Skip existing files on the destination that have a modification time newer
than the source file.
.It Fl v , -verbose
Increase verbosity.
Specify once for files being transferred, twice for specific status,
thrice for per-file transfer information, and four times for per-file
breakdowns.
.It Fl x
Do not cross filesystem boundaries.
If this option is repeated, all mount point directories from the copy are
omitted.
Otherwise, it includes an empty directory at each mount point it encounters.
.It Fl V , -version
Print version and exit.
.El
.Pp
A remote
.Ar source
or
.Ar directory
has the syntax
.Ar host : Ns Ar path
for connecting via
.Xr ssh 1 ,
or
.Cm rsync Ns :// Ns Ar host Ns / Ns Ar path
or
.Ar host Ns :: Ns Ar path
for connecting to a remote daemon.
Subsequent to the first remote
.Ar source ,
the host may be dropped to become just
.Pf : Ar path
or
.Pf :: Ar path .
.Pp
For connecting to a remote daemon with
.Cm rsync Ns :// Ns Ar host
or
.Ar host Ns :: Ns Ar path ,
the first path component is interpreted as a
.Qq module :
.Ar host Ns :: Ns Ar module Ns / Ns Ar path .
This only applies to the first
.Ar source
invocation; subsequent to that, the module should not be specified.
.Pp
By default, new destination files and directories are given the current
time and the source file permissions.
Updated files retain their existing permissions.
It is an error if updated files have their file types change (e.g.,
updating a directory with a file).
.Pp
At this time,
.Ar source
may only consist of regular files, directories
.Pq only with Fl r ,
or symbolic links
.Pq only with Fl l .
The destination
.Ar directory
must be a directory and is created if not found.
.Sh PATTERNS AND RULES
The
.Fl f ,
.Fl -include ,
.Fl -include-from ,
.Fl -exclude ,
and
.Fl -exclude-from
options may be used to load a filter rule or a set of filter rules.
A single filter rule consists of a
.Ar type ,
an optional set of
.Ar modifiers ,
and a
.Ar pattern .
Each
.Ar type
has a short name and a long name.
These will be described in more depth shortly.
.Pp
A filter file is a set of rules, one per line.
Comments are accepted, starting with a
.Sq # .
Empty lines are ignored.
.Pp
Each rule is of the following form:
.Bd -literal
<TYPE>[,<MODIFIERS>] <PATTERN>
.Ed
.Pp
If the short name is used, then the comma separating the modifiers from the rule
type is optional.
The delimiter between the type/modifiers and the pattern may also be an
underbar instead of a space.
.Pp
The following rule types are supported:
.Bl -column -offset indent "LONG NAME" "SHORT NAME" "DESCRIPTION"
.It LONG NAME Ta SHORT NAME Ta DESCRIPTION
.It exclude   Ta - Ta Exclude a file from the transfer
.It include   Ta + Ta Include a file from the transfer
.It merge     Ta . Ta Merge rules in from a file
.It dir-merge Ta : Ta Merge rules in from a per-directory file
.It hide      Ta H Ta Hide a file from the transfer
.It show      Ta S Ta Do not hide a file from the transfer
.It protect   Ta P Ta Protect a file from deletion
.It risk      Ta R Ta Do not protect a file from deletion
.It clear     Ta ! Ta Clear the current filter list
.El
.Pp
The following rule modifiers are supported for the
.Dq exclude
and
.Dq include
rule types:
.Bl -column -offset indent "MODIFIER" "DESCRIPTION"
.It MODIFIER Ta DESCRIPTION
.It / Ta Match against the absolute pathname of the entry
.It ! Ta Take effect if the pattern does not match the entry
.It C Ta Insert the global CVS exclusions
.It s Ta Marks a rule as sender-side only
.It r Ta Marks a rule as receiver-side only
.It p Ta Marks a rule as perishable (do not prevent removal of a directory)
.El
.Pp
The above modifiers will be ignored if applied to other rule types, with the
exception of
.Dq merge
and
.Dq dir-merge
rules.
See the
.Sx Merge Rules
section for more details of the semantics.
.Ss Include and Exclude Rules
The six basic types of include and exclude rules briefly described above are
.Dq exclude ,
.Dq include ,
.Dq hide ,
.Dq show ,
.Dq protect ,
.Dq risk .
.Pp
The
.Dq hide
and
.Dq show
types are sender-side versions of the
.Dq exclude
and
.Dq include
rules, while the
.Dq protect
and
.Dq risk
types are their receiver-side equivalents.
.Pp
Each of these rules take a pattern that is typically matched against the
basename of a transfer candidate's name.
A trailing
.Sq /
in the pattern indicates that the entry should only match a directory name,
while a leading
.Sq /
indicates that the pattern is anchored to the beginning of the transfer path.
The beginning of the transfer path is either the root of the transfer, or the
directory containing a dir-merge file if the rule in question comes from a
dir-merge file.
A
.Sq /
at any other position, or a
.Dq **
in the pattern, will match against the full path to the transfer entry beginning
at the root of the transfer.
.Pp
Patterns may contain any of the following wildcards.
.Bl -column -offset indent "WILDCARD" "DESCRIPTION"
.It WILDCARD Ta DESCRIPTION
.It ?        Ta Matches any character, except Sq /
.It *        Ta Matches zero or more characters, except Sq /
.It **       Ta Matches zero or more characters
.It [        Ta Character class, as in POSIX regular expressions
.It /***     Ta Matches a directory and all of its contents
.El
.Pp
Backslashes may be used to escape one of the above wildcard characters, but is
ordinary when appearing before any other character.
.Pp
Note that exclude rules with the
.Dq C
modifier applied do not take a pattern.
.Ss Merge Rules
The merge rules,
.Dq merge
and
.Dq dir-merge ,
are another way to insert a filter rule file.
.Dq merge
rules are evaluated once as soon as they are processed, and the rules read in
are inserted at the same position as the merge file.
.Dq dir-merge
rules are evaluated as
.Nm
progresses through the file list, searching each directory encountered for the
file named in the rule's pattern.
.Pp
If a
.Dq dir-merge
rule appears before a
.Dq clear
rule, it will not be processed at all.
.Pp
.Dq dir-merge
rules are inserted into their own chain of rules, rather than directly into the
global ruleset.
.Dq clear
rules appearing in a dir-merged file do not affect the global ruleset.
As we find dir-merged files in the transfer, their rules are prepended to their
dir-merge chain so that a deeper directory's rules take precedence over its
parent's rules.
.Pp
When one of the above exclude/include modifiers are applied to
.Dq merge
or
.Dq dir-merge
rule, those modifiers are applied to the exclude/include rules within the file.
The following modifiers may additionally be specified for merge rules:
.Bl -column -offset indent "MODIFIER" "DESCRIPTION"
.It MODIFIER Ta DESCRIPTION
.It -        Ta All rules within are exclude rules
.It +        Ta All rules within are include rules
.It C        Ta File processing should assume CVS-compatible parsing
.It e        Ta Exclude the file's name from the transfer
.It n        Ta Rules are not inherited by subdirectories
.It w        Ta Rules are word-split instead of line-split
.El
.Pp
The CVS-compatible modifier implies the
.Sq - ,
.Sq n
and
.Sq w
modifiers.
If a filename is not supplied with it, then
.Dq .cvsignore
is used.
.Sh ENVIRONMENT
The following environment variables affect execution of
.Nm :
.Bl -tag -width "RSYNC_RSH"
.It Ev RSYNC_RSH
This variable specifies the remote shell to use for remote connections.
The default remote shell is
.Xr ssh 1
if neither
.Ev RSYNC_RSH
nor
.Fl -rsh
are specified.
.El
.\" .Sh FILES
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, 1 if an error occurs, or 2 if the remote
protocol version is older than the local protocol version.
.Sh EXAMPLES
A common invocation of
.Nm
is for archiving from a remote host to the local computer:
.Pp
.Dl % openrsync -av --delete remote:rpath /local/path
.Pp
This will update the contents of
.Pa /local/path/rpath
with those on the remote server.
Switching remote and local wil update the remote contents instead:
.Pp
.Dl % openrsync -av --delete /local/path remote:rpath
.Pp
All examples use
.Fl t
so that destination files inherit the source time.
If not changed, subsequent invocations of
.Nm
will then consider the file up to date and not transfer block hashes.
.Pp
To update the out-of-date remote files
.Pa host:dest/bar
and
.Pa host:dest/baz
with the local
.Pa ../src/bar
and
.Pa ../src/baz :
.Pp
.Dl % openrsync -t ../src/bar ../src/baz host:dest
.Pp
To update the out-of-date local files
.Pa bar
and
.Pa baz
with the remote files
.Pa host:src/bar
and
.Pa host:src/baz :
.Pp
.Dl % openrsync -t host:src/bar :src/baz \&.
.Pp
To update the out-of-date local files
.Pa ../dest/bar
and
.Pa ../dest/baz
with
.Pa bar
and
.Pa baz :
.Pp
.Dl % openrsync -t bar baz ../dest
.Pp
To update the out-of-date remote files in
.Pa host:dest
on a remote host running
.Nm
with the local host running
.Xr rsync 1 :
.Pp
.Dl % rsync --rsync-path openrsync -t ../dest/* host:dest
.\" .Sh DIAGNOSTICS
.Sh SEE ALSO
.Xr ssh 1 ,
.Xr rsync 5 ,
.Xr rsyncd 5
.Sh STANDARDS
.Nm
is compatible with rsync protocol version 27
as supported by the samba.org implementation of rsync.
.Sh HISTORY
The
.Nm
utility has been available since
.Ox 6.5 .
.Sh AUTHORS
The
.Nm
utility was written by
.An Kristaps Dzonsons Aq Mt kristaps@bsd.lv .
.\" .Sh CAVEATS
.\" .Sh BUGS
