name: Build openrsync
on:
  push:
    branches: ['*']
  pull_request:
    types: [opened, reopened]
permissions:
  contents: read
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest]
        include:
          - os: ubuntu-20.04
          - os: ubuntu-22.04
          - os: macos-latest
            cflags: -Wno-error=unguarded-availability-new
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: env CFLAGS="-Werror ${{ matrix.cflags }}" ./configure
      - name: build
        run: make
      - name: smoketest
        run: sh .github/smoke-test.sh
